---
title: "india_monsoon"
author: "Anastacia Wienecke"
date: "`r Sys.Date()`"
output: pdf_document
always_allow_html: true
---

Install and load packages:

```{r include=FALSE}
library(terra)
library(tidyverse)
library(ggplot2)
library(mapview)
library(htmlwidgets)
library(viridis)
library(tidyr)
```

```{r}
### Read in rainfall data (annual per Indian state from 1901-2017)
rains <- read.csv("data/india_rains.csv") %>% 
         select(-Name,-Jan.Feb,-Mar.May,-June.September,-Oct.Dec)

### Compute median and variance in annual rainfall per state
meds <- rains %>%
        group_by(SUBDIVISION) %>%
        summarise_at(vars(ANNUAL), list(median=median, variance=var))
meds$stdev <- sqrt(meds$variance)
meds$stdev.norm <- meds$stdev / meds$median
meds.order <- meds$SUBDIVISION[order(meds$median, decreasing = TRUE)]
```


```{r fig.height = 10, fig.width = 10}
### Plot sampling locations on map, color by median annual rainfall
### At the top left, click the layers button below the zoom function.
### Select "Esri.WorldImagery" to see the satellite view.
latlong <- rains %>%
           select(SUBDIVISION, Latitude, Longitude) %>%
           distinct() %>%
           left_join(meds, by="SUBDIVISION")

minmed <- meds$median %>% min() %>% floor()
maxmed <- meds$median %>% max() %>% ceiling() + 300
breaks <- seq(from=minmed, to=maxmed, by=300)
ranges <- length(breaks)
colors <- rainbow(n = ranges)
india  <- mapview(latlong, xcol = "Longitude", ycol = "Latitude", crs = 4269,
                  grid = FALSE, zcol="median", col.regions = colors, at = breaks)
india
mapshot(india, file = "figures/india.png")
saveWidget(india@map, file="figures/india.html")
```

``` {r fig.height = 10, fig.width = 10, echo=FALSE}
### Assign colors to dataframe
entrys <- latlong$SUBDIVISION %>% length()
shades <- rep('', entrys)
for (i in 1:entrys){
  distances <- latlong$median[i]-breaks > 0
  shades[i] <- colors[distances %>% which() %>% max()]}
latlong$colorful <- shades


### Basic barplots of annual rainfall for 1901, 1925, 1950, 1975, 2000, and 2017
years <- c(1901,1925,1950,1975,2000,2017)
rains.per25years <- rains %>%
                    filter(YEAR %in% years) %>%
                    merge(latlong[c('SUBDIVISION', 'colorful')], 
                          by=c("SUBDIVISION"))
meds.factor <- factor(rains.per25years$SUBDIVISION, levels=meds.order)
rains.per25years <- rains.per25years[order(meds.factor),]
rains.per25years$SUBDIVISION <- factor(rains.per25years$SUBDIVISION,
                                       levels = meds.order)

bars <- ggplot(data=rains.per25years, aes(x=SUBDIVISION, y=ANNUAL,
                                          fill=colorful)) +
               geom_bar(stat="identity", show.legend = FALSE) +
               scale_x_discrete(guide = guide_axis(angle = 90)) +
               facet_grid(YEAR ~ ., scales = "free_y") +
               coord_cartesian(ylim = c(0, 4500)) +
               labs(x = "State",
                    y = "Median Rainfall",
                title = "Barplot of annual rainfall for years 1901, 1925, 1950,
                1975, 2000, and 2017")
bars
ggsave("figures/quarter_century_rainfall.png", bars)
```

``` {r echo=FALSE}
### Median monthly rainfall for each state
rains.col <- merge(rains, latlong[c('SUBDIVISION', 'colorful')],
                   by=c("SUBDIVISION"))
indexs <- c(1,2,3,4,5,8,9,11)
graphs <- list()
count  <- 1
for(i in indexs){
rains.info <- rains.col %>%
              filter(colorful %in% colors[i]) %>%
              pivot_longer(
                cols = JAN:DEC,
                names_to = "month",
                values_to = "rainfall") %>%
              group_by(month,SUBDIVISION) %>%
              summarise_at(vars(rainfall), 
                           list(median=median,
                                Q1=~quantile(., probs = 0.25),
                                Q3=~quantile(., probs = 0.75)))
rains.info$month <- factor(rains.info$month, levels = c("JAN", "FEB", "MAR",
                                                        "APR", "MAY", "JUN",
                                                        "JUL", "AUG", "SEP",
                                                        "OCT", "NOV", "DEC"))

graphs[[count]] <- ggplot(rains.info, aes(month, median, color=SUBDIVISION,
                                          group=SUBDIVISION)) +
                          geom_point() +
                          geom_line() +
                          #geom_errorbar(aes(ymin = Q1, ymax = Q3)) +
                          labs(x = "month",
                               y = "median rainfall between 1901 and 2017")
ggsave(paste('figures/median_monthly_rainfall_lineplot',as.character(count),'.png',
             sep=''), graphs[[count]] )
count <- count + 1 
}
graphs
```

``` {r}
### Comparison of median annual rainfall and the standard deviation in annual rainfall
# Non-normalized
nnorms <- ggplot(data=meds, aes(x=median, y=stdev)) +
                 geom_line() +
                 geom_point() +
                 labs(x = "Median Annual Rainfall",
                      y = "Standard Deviation in Annual Rainfall",
                  title = "Line plot of median annual rainfall vs. the standard
                  deviation in annual rainfall")
ggsave("figures/lineplot_median_stdev_rainfall.png", nnorms)
nnorms

# Normalized
norms <- ggplot(data=meds, aes(x=median, y=stdev.norm)) +
                geom_line() +
                geom_point() +
                labs(x = "Median Annual Rainfall",
                     y = "Scaled Standard Deviation in Annual Rainfall",
                 title = "Line plot of median annual rainfall vs. the scaled
                 standard deviation in annual rainfall\n(standard deviation
                 divided by median)")
ggsave("figures/lineplot_median_norm_stdev_rainfall.png", norms)
norms
```
